---
channel: edge
addons:
  code-server:
    repository: elcajon/app-code-server
    target: code-server
    image: ghcr.io/elcajon/code-server/{arch}
  app-assistant:
    repository: elcajon/app-assistant
    target: app-assistant
    image: ghcr.io/elcajon/app-assistant/{arch}
